{{- if .Values.gateway.enabled }}
apiVersion: {{ .Values.gateway.apiVersion }}
kind: Gateway
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
{{- if .Values.gateway.annotations }}
  annotations:
    {{- toYaml .Values.gateway.annotations | nindent 4 }}
{{- end }}
spec:
   {{- if  .Values.gateway.class }}
  gatewayClassName: {{ .Values.gateway.class }}
  {{- end }}
  {{- if .Values.gateway.addresses }}
  addresses:
    {{- toYaml .Values.gateway.addresses | nindent 2 }}
  {{- end }}
  listeners:
  {{- range .Values.gateway.listeners }}
  - name: {{ .name }}
    protocol: {{ .protocol }}
    port: {{ .port }}
    {{- if .hostname }}
    hostname: {{ .hostname | quote }}
    {{- end }}
    {{- if .tls }}
    tls:
      mode: {{ .tls.mode }}
      certificateRefs:
        {{- range .tls.certificateRefs }}
        - name: {{ .name }}
          kind: {{ .kind | default "Secret" }}
          {{- if .namespace }}
          namespace: {{ .namespace }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- if .allowedRoutes }}
    allowedRoutes:
      kinds:
      {{- range .allowedRoutes.kinds }}
      - group: {{ .group | default "gateway.networking.k8s.io" }}
        kind: {{ .kind }}
      {{- end }}
      namespaces:
        from: {{ .allowedRoutes.namespaces.from }}
        {{- if .allowedRoutes.namespaces.selector }}
        selector:
          matchLabels:
            {{- toYaml .allowedRoutes.namespaces.selector.matchLabels | nindent 14 }}
          matchExpressions:
            {{- toYaml .allowedRoutes.namespaces.selector.matchExpressions | nindent 14 }}
          {{- end }}
      {{- end }}
  {{- end }}
{{- end }}