{{- range .Values.httproutes }}
{{- if .enabled }}
apiVersion: {{ $.Values.apiVersion }}
kind: HTTPRoute
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
  {{- toYaml .parentRefs | nindent 3 }}
  hostnames:
  {{- toYaml .hostnames | nindent 3 }}
  rules:
  {{- toYaml .rules | nindent 3 }}
---
{{- end }}
{{- end }}